[package]
name = "archive-unrar"
version = "0.1.0"
authors = ["Fredrik Jonsén <frjonsen@users.noreply.github.com>"]
edition = "2018"

[dependencies]
unrar = "0.4.3"
clap = "2.33.0"
env_logger = "0.6.1"
log = "0.4.0"